### ISSUE TITLE
Schema validation fails, when a number is expected and set in a config file, i.e. igenomes.config

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/tools#1634]
### Description of the bug

If a parameter is passed to a pipeline via the command line that looks like a number, the `nextflow_schema.json` should contain a number (apparently because groovy aggressively tries to cast things passed via the command line). 
However, if the same value is set in a config file, i.e. the igenomes.config, it is read as a String and fails parameter validation.

For the example below (it is important here not to use the test.config (there everything works as expected))

### Command used and terminal output

```console
nextflow run nf-core/sarek -r dev -profile docker --input tests/csv/3.0/fastq_pair.csv



Output:

ERROR: Validation of pipeline parameters failed!


* --vep_cache_version: expected type: Number, found: String (104)


This works as expected (but we don't want the user to have to set this parameter since it is a reference value we already provide):

nextflow run nf-core/sarek -r dev -profile docker --input tests/csv/3.0/fastq_pair.csv --vep_cache_version 104 
```

### System information

nextflow version 22.04.3.5703
Desktop
local
macOS

**Comment by SamStudio8** [comment]
Out of curiosity I had a look around the `sarek` dev branch to see if I could make sense of this, as we’ve also encountered many oddities around config parsing differences between the CLI and config files and thought there might be some relation! I noticed that [main.nf reassigns the value of `params.vep_cache_version`](https://github.com/nf-core/sarek/blob/dev/main.nf#L54) via a call to [`getGenomeAttribute` in WorkflowMain](https://github.com/nf-core/sarek/blob/dev/lib/WorkflowMain.groovy#L85); and crucially this is done before the `nf-core` validation is performed.

I believe your numeric values are being coerced back to strings by `getGenomeAttribute` because the function definition specifies the return type is a `String`. You can confirm this intuition with a little bit of Groovy:

```
public static String getVal() {
    def val = ''
    val = 104
    println("Inside...")
    println(val.getClass())
    println(val)
    return val
}

def val = getVal()
println("Outside...")
println(val.getClass())
println(val)
```

```
Inside...
class java.lang.Integer
104
Outside...
class java.lang.String
104
```

Hope this helps!

**Comment by maxulysse** [comment]
More related issue.
Also with doubles.
I'll look into @SamStudio8 idea's
```
ERROR: Validation of pipeline parameters failed! 
* --vep_version: expected type: String, found: Double (104.3)
```

**Comment by maxulysse** [comment]
Also, I'm getting similar issues not only from `getGenomeAttribute`, but from `validateParameters` I think. so definively an issue worth discussing in `#tools`.

**Comment by maxulysse** [comment]
@SamStudio8 I'm trying out https://github.com/nf-core/tools/pull/1667

**Comment by mirpedrol** [comment]
I am closing the issue as it seems to be fixed by [#1667](https://github.com/nf-core/tools/pull/1667), thanks!

**Comment by maxulysse** [comment]
I'll try that out right away then

**Comment by maxulysse** [comment]
Wait, I had that part already...
But I can't reproduce my errors anymore...
I am confused now...

**Comment by mirpedrol** [comment]
Wasn't it fixed by you @maxulysse ?

**Comment by maxulysse** [comment]
I still had issues even with that, but can't reproduce anymore.
So let's say it's fixed

**Comment by maxulysse** [comment]
Reproduced my issue:
So no problem if it's set up in `igenomes.config`, that's indeed what I fixed in #1667 
But still failing when specified on the command line:
```
nextflow run maxulysse/nf-core_sarek -r dev_number_validation -profile test,annotation,docker --tools snpeff --snpeff_version 5.1 --vep_cache_version 106 --vep_version 106.1
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/maxulysse/nf-core_sarek` [jolly_gutenberg] DSL2 - revision: 289aa53296 [dev_number_validation]

ERROR: Validation of pipeline parameters failed!


* --snpeff_version: expected type: String, found: Double (5.1)


* --vep_version: expected type: String, found: Double (106.1)
```

cf https://github.com/nf-core/sarek/pull/690

**Comment by SamStudio8** [comment]
@maxulysse Is this not because the types are defined as `string` in the `nextflow_schema`? https://github.com/nf-core/sarek/blob/dev/nextflow_schema.json#L668.
